// swift-tools-version: 5.9

import PackageDescription

let package = Package(
    name: "LdgrSwift",
    platforms: [
        .iOS(.v16),
        .macOS(.v13),
        .watchOS(.v10),
    ],
    products: [
        .library(
            name: "LdgrSwift",
            targets: ["LdgrSwift"]
        ),
    ],
    targets: [
        // XCFramework containing the compiled Rust cdylib
        .binaryTarget(
            name: "ldgr_ffiFFI",
            path: "Frameworks/ldgr_ffiFFI.xcframework"
        ),
        // UniFFI-generated Swift bindings (auto-generated by build script)
        .target(
            name: "LdgrFFI",
            dependencies: ["ldgr_ffiFFI"],
            path: "Sources/LdgrFFI"
        ),
        // Idiomatic Swift async/await wrapper layer
        .target(
            name: "LdgrSwift",
            dependencies: ["LdgrFFI"],
            path: "Sources/LdgrSwift"
        ),
        .testTarget(
            name: "LdgrSwiftTests",
            dependencies: ["LdgrSwift"],
            path: "Tests/LdgrSwiftTests"
        ),
    ]
)
