// This directory holds UniFFI-generated Swift bindings.
//
// The file `ldgr_ffi.swift` is auto-generated by the build script:
//   cd bindings/swift && ./build-xcframework.sh
//
// Do NOT edit the generated file manually.
// To regenerate after Rust API changes, re-run the build script.
//
// This placeholder exists so SPM can resolve the target before generation.

// Generated bindings are imported by LdgrSwift via `import LdgrFFI`.
